services:
  backend:
    image: ghcr.io/flyingt/belegt-backend:latest
    container_name: belegt-backend
    expose:
      - "5000"
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-belegt}
      - TZ=Europe/Berlin
      # - ALLOWED_ORIGINS=http://localhost:3000
      # - SECRET_KEY=mein-geheimer-schluessel
    volumes:
      - belegt-backend_data:/app/instance
    restart: unless-stopped
    networks:
      - belegt-network

  app:
    image: ghcr.io/flyingt/belegt-frontend:latest
    container_name: belegt-frontend
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - belegt-network

volumes:
  belegt-backend_data:

networks:
  belegt-network:
    driver: bridge
